### ISSUE TITLE
haplotype coordinates in GRCh38

### ISSUE THREAD

**Issue by ekg** [nouyang-curoverse/GA4GH_regions#1]
I'd like to figure out where these haplotypes came from. Unfortunately, I can't seem to find the epost utility that you used to get the coordinates. Where is this from?

**Comment by ekg** [comment]
Whoops, it seems `GeneRefSeqCoordinates` has what I want.

**Comment by nouyang-curoverse** [comment]
@ekg  I could pull the coordinates from that folder out into a spreadsheet, if you think other people would find it helpful for verifying the files.

**Comment by ekg** [comment]
What I just realized is that I'm after something different, which is where
the haplotypes map in the complete chromosomes in the genome.

This would greatly simplify the process of constructing a graph from them.

**Comment by ekg** [comment]
[I think I've found the information I'm after](https://twitter.com/dnadiver/status/571284488128471041). It's just a table of mappings between the alts and the primary chromosomes @ ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA_000001405.15_GRCh38/GCA_000001405.15_GRCh38_assembly_structure/all_alt_scaffold_placement.txt.

**Comment by nouyang-curoverse** [comment]
@ekg Awesome that you got an answer on twitter!
